# Generated by Django 5.2.14 on 2026-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='no value', max_length=100),
            preserve_default=False,
        ),
    ]
